emacs-evil/evil

- README.md
> Fix pdf manual URL

- evil.el
> Fix repo url in commentary section

- evil-commands.el
- evil-common.el
- evil-core.el
- evil-ex.el
- evil-macros.el
- evil-pkg.el
- lib/undo-tree.el
The logical continuation of #770
> Remove support for Emacs < 24

- evil-common.el
- evil-ex.el
See discussion in https://github.com/emacs-evil/evil/pull/771
> Re-add compatibility functions with deprecation warnings

- evil-commands.el
> make  evil-paste-before respect evil-move-cursor-back

- evil-commands.el
> Keep C-w in insert state from saving deleted text

- evil-common.el
> Use `save-excursion` to preserve point

- evil-vars.el
This is another remnant of the hg -> git conversion.
> Remove hg check, change cond to if

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- README.md
This should hopefully improve the quality of bug reports.  I've taken the liberty of moving the existing bug report section to a `CONTRIBUTING.md` file.
> Add issue template, move bug report section

- evil-ex.el
- evil-tests.el
> Support numbers in Emacs commands for ex

- evil-commands.el
nxml-mode somehow changes the match data during the course of using
evil-ex-substitute with the gc flags. Make evil-ex-substitute very careful about
using the right match-data for moving point and performing replacements. This
should not be necessary, but I guess we can't rely on modes to be careful about
not overwriting the match data randomly.
Fixes #859
> Fix regression in evil-ex-substitute with nxml-mode

- evil-integration.el
So it can be used when in pending operation state.
> Add evil-avy-goto-char-timer

- evil-maps.el
> Map <C-w> q to evil-quit

- evil-vars.el
> Add vdiff fold integration

- evil-commands.el
- evil-vars.el
> Don't abort macro recording when current buffer is changed

- evil-core.el
In evil-define-key, allow keymap to be 'global, 'local or some other quoted
symbol, which is assumed to be a minor mode.
Using 'global, corresponds to making a global binding in the corresponding
global evil keymap (similar to evil-global-set-key). Using 'local, corresponds
to making a local binding in the corresponding local evil keymap (similar to
evil-local-set-key).
Any other quoted symbol is assumed to be the name of a minor mode, and the
binding is dispatched to evil-define-minor-mode-key.
Make evil-define-key* support global and local symbols.
Allow a list of states in evil-define-minor-mode-key.
This makes evil-define-key serve as a general keybinding function.
> Generalize use of KEYMAP in evil-define-key

- README.md
this only touches 3 lines of the readme adding some standard badges.
> add travis, melpa and GPLv3 badges

- evil-commands.el
- evil-tests.el
> :global should take into account evil-ex-search-case

- evil-core.el
- evil-macros.el
- evil-vars.el
Time to share the goodie which was for a long time in my private version of Evil.  I saw a number of people on the web looking for this support.  Enjoy!
> Add option to enable Evil in minibuffer(s)

- evil-maps.el
> fix: check value of evil-want-C-d-scroll at load time

- evil-vars.el
Refs https://github.com/justbur/emacs-vdiff/issues/22
> Support toggling vdiff folds

- evil-ex.el
- evil-tests.el
> Handle dash in ex commands

- evil-repeat.el
> Ignore mouse events for repeat info

- evil-ex.el
- evil-tests.el
> Fix erroneously short-parsing Emacs commands

- evil-commands.el
- evil-search.el
- evil-vars.el
See also https://github.com/emacs-evil/evil/pull/869#issuecomment-314392574
> Change evil-goto-definition to use a hook

- evil-commands.el
> Fix usage of too new macro `ignore-error'

- evil-commands.el
> Handle empty buffer when shifting left/right

- evil-vars.el
> Support to toggling in vdiff-3way-mode

- Cask
- evil-command-window.el
- evil-commands.el
- evil-common.el
- evil-core.el
- evil-development.el
- evil-digraphs.el
- evil-ex.el
- evil-integration.el
- evil-jumps.el
- evil-keybindings.el
- evil-macros.el
- evil-maps.el
- evil-pkg.el
- evil-repeat.el
- evil-search.el
- evil-states.el
- evil-test-helpers.el
- evil-tests.el
- evil-types.el
- evil-vars.el
- evil.el
> Release 1.2.16

- README.md
> Update README to point to new docs

- evil-commands.el
> Fix final cursor after shifting

- evil-command-window.el
- evil-commands.el
- evil-common.el
- evil-core.el
- evil-development.el
- evil-digraphs.el
- evil-ex.el
- evil-integration.el
- evil-jumps.el
- evil-keybindings.el
- evil-macros.el
- evil-maps.el
- evil-repeat.el
- evil-search.el
- evil-states.el
- evil-test-helpers.el
- evil-types.el
- evil-vars.el
This reverts commit c6086a7b0b44963071096e3ed7545f617de88915.
Due to #1257
> Revert "Enable lexical binding"

- evil-common.el
- Fixes https://github.com/emacs-evil/evil/issues/1260
```elisp
(advice-add 'evil-set-register :around
(lambda (orig register text)
(if (eq register ?\) )
(evil-append-register ?0 text)
(funcall orig register text))))
```
> Extract evil-append-register function

- doc/source/keymaps.rst
I found a spelling error while reading through the documentation.
> Spelling fix

- evil-common.el
- evil-core.el
- evil-ex.el
> evil-add-to-alist: convert to macro for lexical binding

- evil-core.el
> fix evil-send-localleader

- evil-maps.el
- evil-vars.el
`g C-g` to count words in motion state
> Binding "g C-g" to count words

- evil-commands.el
> evil-visual-paste does not respect evil-kill-on-visual-paste

- evil-commands.el
> Revert change to evil-delete-char

- evil-commands.el
- evil-tests.el
> Fix 1365: Respect nil `evil-kill-on-visual-paste'

- evil-commands.el
- evil-maps.el
- evil-tests.el
- evil-types.el
:goto seems to be broken. This is a fix with tests.
> Fix evil goto char

- evil-commands.el
Just noticed that evil puts the cursor on the end of line or beginning of line for evil-next-mark-line and evil-previous-mark-line respectively, even when there are no marks present in the buffer. This fixes that.
> Fix goto-eol behaviour on failed next-mark line

- evil-search.el
> Fix evil-ex-search-backward stuck on first match

- evil-commands.el
- evil-tests.el
Short recursive solution is more readable and gives better errors messages.
> Refactor evil-delete-marks code & add better errors

- evil-repeat.el
- evil-tests.el
> Save and restore `evil-last-find` when doing `evil-repeat`

- evil-commands.el
- evil-common.el
- evil-maps.el
- evil-tests.el
> Evil ex put

- evil-commands.el
> evil-show-registers: invoke evil-register-list within current buffer

- evil-ex.el
- evil-tests.el
- evil-types.el
> Fix 1482 addr wraparound

- evil-commands.el
- evil-states.el
- evil-tests.el
Less problematic approach for #1487
> evil-maybe-remove-spaces works for cc<escape>

- .github/ISSUE_TEMPLATE.md
- README.md
- doc/source/overview.rst
- evil.el
- scripts/evilupdate
See https://github.com/emacs-evil/evil/issues/1507.
> Mention NonGNU ELPA

- evil-ex.el
> Don't abort ex if choosing completion with mouse

- evil-ex.el
- evil-tests.el
Fixes #1192.
I committed under @nnicandro's name. I think squash-merging them may incorrectly attribute authorship to me, whereas rebasing should correctly assign authorship to him.
> Handle more registers and range types in ex grammar

- evil-commands.el
- evil-tests.el
> Handle charwise >1 line deleting as linewise

- evil-commands.el
- evil-tests.el
> evil-read: Handle substitutions for shell cmds

- evil-commands.el
- evil-tests.el
> Don't ex move if source = destination

- evil-commands.el
- evil-ex.el
- evil-macros.el
- evil-tests.el
In visual state, it restores point to beginning of visual range
Fixes #1593
> Ex yank doesn't move point

- evil-ex.el
- evil-tests.el
> Ensure we're not in visual state if there's no ex range

- evil-commands.el
- evil-tests.el
> Preserve non-blank last line when :move ing

- evil-commands.el
- evil-common.el
- evil-tests.el
> Block visual paste

- evil-maps.el
Add `:tabclose` and `:tabonly` for closing tabs to go along with `:tabnew` and friends.
> Add ex commands for closing tabs

- evil-commands.el
- evil-common.el
- evil-tests.el
> Add `evil-word-object` & `evil-WORD-object` which stay on line

- doc/source/settings.rst
- evil-commands.el
- evil-tests.el
- evil-types.el
- evil-vars.el
Deprecate `evil-want-visual-char-semi-exclusive`.
Fixes #897
> Add `evil-v$-excludes-newline`

- evil-commands.el
> Improve on evil-append's determination of eolp

- evil-ex.el
- evil-tests.el
- evil-vars.el
> Handle reverse ex ranges

- evil-commands.el
- evil-tests.el
> Enable moving from point-min for next flyspell error

- evil-ex.el
- evil-search.el
- evil-vars.el
> Store :/ search pattern and parse vim-style regexp

- evil-common.el
- evil-repeat.el
- evil-tests.el
- evil-vars.el
> Store digraph character directly for repetition

- evil-ex.el
An empty string will not parse as an Ex command, meaning `evil-ex-cmd` would be nil even after `evil-ex-update` returns. This pull request makes sure `evil-ex-command-completion-at-point` handles this.
Also remove the unnecessary nil-check in `evil-ex-binding`.
> Fix Ex completion of empty string

- evil-commands.el
- evil-common.el
- evil-core.el
- evil-ex.el
- evil-jumps.el
- evil-repeat.el
- evil-search.el
- evil-types.el
- evil-vars.el
> doc: follow the Emacs Lisp Style Guide

- evil-common.el
> Ensure column doesn't spoof `next-line`

- evil-commands.el
- evil-search.el
- evil-tests.el
> Fix evil-ex-substitute up to EOB

- evil-maps.el
- evil-search.el
- evil-tests.el
- evil-vars.el
> C-w support yank word when search-module is 'evil-search

- doc/source/settings.rst
- evil-commands.el
- evil-states.el
- evil-vars.el
> evil transient mouse selection

- evil-commands.el
- evil-tests.el
> Flush and keep for evil-ex-global performance

- evil-vars.el
> evil-show-paren-range: fix incorrect docstring

- evil-commands.el
- evil-tests.el
> Fix Normal mode "D"/"C" with count

- evil-integration.el
Instead of positioning the point and narrowing correctly for the entirety of `show-paren-function`, just do it for the `show-paren-data-function` call. This avoids duplicating the logic for removing stale overlays, which had to support both the new and old names of the once renamed `show-paren--overlay` variables.
Not narrowing during `show-paren-function` also fixes an issue with the `mixed` `show-paren-style`, which uses `pos-visible-in-window-p`, see #1739.
Closes #1739
> Wrap just show-paren-data-function in advice

- evil-common.el
- evil-ex.el
- evil-search.el
- evil-tests.el
- evil-vars.el
See individual commits.
On my machine this pull request makes `make test` 40% faster, however the test suite not being byte- nor native compiled makes that figure less interesting.
> Compile Ex parser

- evil-vars.el
Otherwise it will pop an error after this commit
https://github.com/emacs-mirror/emacs/commit/802a54ad620
For ref: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=62248
> Add the missing quote for obsolete

- evil-commands.el
> Assign :jump to evil-{next-close,previous-open}-{brace,paren}

- evil-repeat.el
- evil-tests.el
> Handle args-out-of-range error in evil-repeat-start

- evil-commands.el
- evil-maps.el
- evil-tests.el
Most of the work was done by Maxi Wolff (@smile13241324) over 6yrs ago. I've made a few changes, so have assumed authorship.
This fixes #968
> Add handler for expanding line for line-based operators

- evil-commands.el
- evil-common.el
- evil-tests.el
> Visual eol anchoring, so g$ is sticky

- evil-commands.el
- evil-tests.el
> Record search offset for repeat

- evil-commands.el
> Add c-ts-mode to evil-jump-item c major modes

- evil-ex.el
> Call evil--ex-update one last time in minibuffer teardown

- .github/workflows/test.yml
> ci: Test latest Emacs 29.4

- evil-keybindings.el
> Update speedbar keybindings map
