emacs-evil/evil

evil.el
This is a follow up of #753 and #754. Corrected other locations that needed to be updated to reflect evil's new home, bug tracking location and mantainer information.
=> further update information about evil's new home.

doc/evil.texi, scripts/evilupdate
following up on @wasamasa's [comment](https://github.com/emacs-evil/evil/pull/759#issuecomment-278587741), this further complements #753, #754 and #759 updating additional instances of official repository locations found in docs and scripts directories.
=> further update repository information in docs and scripts directories

evil-common.el, evil-jumps.el, evil-pkg.el, scripts/evilupdate
As parts of Evil have already been using `cl-loop` from `cl-lib` while others still relied on unprefixed `cl.el` functionality (more specifically, `incf`), I've taken the liberty to remove all `cl.el` usage.  A side effect of this is that Evil depends on `cl-lib` to accomodate for older Emacsen (24.1 and 24.2?) that don't have it included, for them the dependency can be installed from GNU ELPA.  This also means that code specific to Emacs 23 should be deleted as Emacs 23 isn't compatible with cl-lib and we don't test it anyways.
The biggest change is the dropped `lexical-let` from `evil-select-paren`.  I've thought for quite a while about why one would want to bind a variable to its value and came up with two cases:
1. The body of the let mutates one of the bindings which happen to refer …
=> Require cl-lib instead of cl

evil-commands.el
`scroll-preserve-screen-position' is a user settable variable that
controls scroll-up/scroll-down's behavior.
Set it to nil before calling scroll-* so that the cursor stays on the
same line it was already on after scrolling.
https://github.com/emacs-evil/evil/issues/734
=> Match C-e/C-y scrolling behavior with Vim's

evil-commands.el, evil-tests.el
See #794.
Notes:
- This doesn't handle a sequence like `R C-3 i <backspace> <backspace> <backspace>` correctly.  Note how repetition of insertion works as expected (I've fixed a case of swapped arguments for this), but undoing doesn't.  While this peeves me greatly, Vim doesn't even allow specifying a prefix arg in replace state, so that's fine I guess.
- I've noticed that `C-e` in replace state runs the appropriate Emacs command, not the copying command.  To make the example from the linked issue work out of the box, `evil-replace-state-map` would need to get augmented, then the respective lines in the tests could be omitted.  I don't think that's part of the PR though...
=> Correct C-e and C-y in replace state

evil-commands.el, evil-search.el, evil-tests.el
With this change, you can for example:
1. search for foo `/foo`
2. delete all lines with foo with `:g//d`
Without this commit, `:g//d` would delete *all* lines in the buffer since the empty `""` pattern matches on every line.
Please, let me know if the PR can be improved.
=> :global should use last pattern if none given

evil-commands.el, evil-tests.el
When the search string is a newline and evil-move-beyond-eol is nil, point gets
moved back an extra character after moving to the beginning of the matched
character (the newline). evil-search-next then finds that same newline again and
we get stuck.
Add regression test.
Fixes #823
=> Fix evil-search-next when search string is newline

evil-commands.el, evil-common.el, evil-maps.el, evil-tests.el, evil-types.el
With this change, `:delete` can be called like so:
- `:d 2` to del 2 lines
- `:d x` to del the line and put the text into register `x`
- `:d x 2` to del 2 lines into register `x`
Passing COUNT while in visual mode works a bit strange in my opinion, but the behaviour should be the same as in vim.
Also, I'm not sure function `evil-ex-get-delete-info` should be in evil-types.el, but I couldn't find a better place.
As always, please let me know if the PR can be improved.
Refs #760
=> Add support for passing REGISTER and COUNT to :delete

Makefile
As discussed in #822, with this, `make emacs` will not run emacs in the background
=> Don't run in emacs in background with "make emacs"

evil-commands.el, evil-vars.el
This change has been applied to get closer to Vim.  While C-u and C-d in Vim remember the last scroll amount, the Vim manual mentions nothing of this sort about C-y and C-e.
Closes #790.
=> Don't reuse scroll line count

evil-vars.el
It doesn't make much sense to have it here because initial states apply to major modes only.  For minor modes, use a hook.
Prompted by http://emacs.stackexchange.com/a/32133/10
=> Remove view-mode (minor mode) from initial states

evil-commands.el
With point on a word, :%s/<C-r><C-w> gives an end of buffer warning from the
forward-char at the end of evil-paste-from-register.
=> Fix minor issue with evil-paste-from-register

evil-common.el
This fixes issues with text objects. For example, if we run the code:
(evil-define-text-object inner-racket-comment (count &optional beg end type)
(evil-select-paren "#|" "|#" beg end type count nil))
(evil-define-text-object outer-racket-comment (count &optional beg end type)
(evil-select-paren "#|" "|#" beg end type count t))
(define-key evil-inner-text-objects-map "#" 'inner-racket-comment)
(define-key evil-outer-text-objects-map "#" 'outer-racket-comment)
then we go to some text like this (where ? will represent the cursor position):
#|this is? a test #|with rackety|# multiline
and nestable comments|#
then hit vi# we get the following (with < and > denoting the visual range endings)
#|this is a test #|<with rackety>|# multiline
and nestable comments|#
This patch makes it work as …
=> fix evil-up-block

evil-commands.el, evil-tests.el
Zero length regexps, particularly "$", may get matched over and over. Also add a
test for this.
Fixes #849
=> Prevent infinite loop in evil-ex-substitute

evil-commands.el, evil-vars.el
Allows one to prevent evil-visual-paste from automatically adding the replaced
text to the kill ring, which changes what will be pasted next.
It may just be me, but I hate the default vim behavior of essentially yanking the replaced text. I don't see why you would want to replace some text with a paste and then paste the replaced text somewhere else.
This is a simple change to make in the evil source that would be difficult to accomplish with an external plugin.
=> Add evil-kill-on-visual-paste option

evil-common.el, evil-tests.el
=> Keep Emacs from clearing text properties on yank

evil-core.el
This avoids having to input ESC ESC ESC in Terminals when trying to
exit out of Minibuffer/Ivy/Helm/etc.
Can then write something like this for Ivy to escape out.
```
(eval-after-load 'evil
(lambda ()
(define-key ivy-minibuffer-map [escape] 'minibuffer-keyboard-quit)))
```
=> Use evil-esc in minibuffers

evil-commands.el
Usually I am using a one year outdated evil-mode because [of a regression](https://github.com/emacs-evil/evil/issues/684), and with occasional recent update I found the vanilla evil is missing this nice little feature of using semantic and tags.
So I thought others might be happy to get this as well. I've used this code for may be a year *(cleaned up a bit though before the commit).
=> Wire up semantic and tags for "goto-definition" when available

evil-common.el
Without this fix, actions such as `d C-v 5 j` would occasionally fail
with such errors `Wrong type argument: wholenump, 6.0`
=> Truncate temporary-goal-column which might be a floating number

evil-test-helpers.el
- add Package-Requires header
- fix byte compile warning about evil-test-selection
- move call to `provide` to the bottom of the file
Refs https://github.com/melpa/melpa/pull/4837
Refs https://github.com/emacs-evil/evil/issues/846
=> Cleanup evil-test-helper.el

evil-commands.el, evil-tests.el
I'm beginning to not want to be responsible for this function. In dealing with the special case where `:%s/$/ TEST/` can loop infinitely because point never moves past the first "$", I think I introduced the regression in #881. With the line "xxxx" in the buffer `:s/x//` in the old version would skip over every other "x" because it accidentally identified the match as having zero length. 
It's not the prettiest piece of work, but I think I've dealt with the special cases here in a fairly robust way. I added three tests, and a bunch of comments to the code to explain. 
Please review
=> Fix evil-ex-substitute (#881)

evil-common.el, evil-tests.el
Fixes issue #884.
The code assumed (badly) that the start and end patterns were distinct.  If the start and end patterns are the same it was looping until hitting the end of the buffer.  This fixes the balancing behavior to not try to balance delimiters that are the same on both sides.
=> fix pipe text-object macro

evil-common.el, evil-integration.el, evil-vars.el
Supersedes #901 
Remap commands to use visual version when `visual-line-mode` is active.
These commands are swapped
```
evil-next-line         <-> evil-next-visual-line
evil-previous-line     <-> evil-previous-visual-line
evil-beginning-of-line <-> evil-beginning-of-visual-line
evil-end-of-line       <-> evil-end-of-visual-line
```
**Note**: I previously thought reworking yy, dd, pp, and so on was worth it here, but I changed my mind. I don't think the behavior is that intuitive (at least how I did it), and I think using specific motions like d$ are a better choice.
=> Add evil-respect-visual-line-mode option

evil-integration.el
Currently Evil breaks `term-char-mode` undo by enabling `undo-tree-mode`, see
https://github.com/syl20bnr/spacemacs/issues/4063#issuecomment-162913414
`turn-on-undo-tree-mode` checks the variable `undo-tree-incompatible-major-modes`
before enabling `undo-tree-mode`, see https://github.com/emacs-evil/evil/blob/master/lib/undo-tree.el#L2618
=> Fix term-mode undo issue

evil-commands.el, evil-vars.el
This patch adds a new variable, `evil-change-commands`, which defines
functions that evil will treat as bound to 'c'. When wrapping
`evil-change`, add your function to this list to get the same behavior
as `evil-change`.
Let me know if anyone spots anything wrong, or if you think this can be improved.
Also, thanks so much for maintaining evil, it's a huge part of my life :smile:
Closes #916
=> evil-commands.el: Add a configurable list of evil-change commands

.dir-locals.el
This PR adds a trivial dir-locals file which overrides `indent-tabs-mode` to nil in emacs-lisp files.
Let me know if you think anything else should be added (fill-column, indention level, etc).
=> Add a dir-locals file

evil-commands.el
Fix #932
Sample error message:
`Folding is supported for these major/minor modes: hs-minor-mode, hide-ifdef-mode, outline-mode, origami-mode`
Let me know if the message can be improved.
=> Extend error message when folding isn't supported

evil-common.el
Some major modes in emacs have variable yank-excluded-properites as t that means to discard all text properties when yanking. With the old evil-yank-line-handler function this case is not correctly implemented, only discards text properties when yank-excluded-properties is a list. With the old function there is a bug that with web-mode and evil-mode activated in a buffer, when you yank whole line with `yy` and then paste the yanked line, if you copy a piece of text of the yanked line and paste it, the pasted text appears in a new line and truncated. With this commit this bug is fixed.
=> Fixed evil-yank-line-handler and evil-yank-block-handler when yank-excluded-properties is t

evil-common.el
The docstrings for `evil-select-inner-object` and `evil-select-an-object` reference the arguments FORWARD and BACKWARD, which don't exist.  This PR just removes them.
Fixes #838
=> Remove reference to missing arguments FORWARD and BACKWARD from doc

evil-commands.el
Documented the dependency from 'evil-cross-lines' custom variable.
=> Extended docstring for evil-find-char.

evil-ex.el
With this PR evil's ex completion will load an autoloaded function before providing completion.
For example, the following scenario will work:
1. external package [evil-expat](https://github.com/edkolev/evil-expat) will define ex command `:rename NEW-NAME` (which moves/renames the current file and its buffer) with an autoload cookie like  so:
```emacs-lisp
(evil-define-command evil-expat-rename (bang new-name)
"Rename the current file and its buffer to NEW-NAME..."
(interactive "<!><f>")
...)
;;;###autoload
(eval-after-load 'evil
'(progn
(evil-ex-define-cmd "rename" 'evil-expat-rename)
(autoload 'evil-expat-rename "evil-expat" nil t)))
```
2. the evil-expat-autoloads.el file is loaded by `(package-initialize)`
3. when the user enters `:rename /tm<TAB>` the evil-expat package will be …
=> If an autoload, load ex function so completion can be provided

.travis.yml, Makefile
This PR is an attempt to fix the CI segfaults that we've been dealing with.
The main change is that EVM (and its binaries) is not used. Instead, the emacs binaries from this repo are used https://github.com/npostavs/emacs-travis
These are the same binaries used by magit since this PR https://github.com/npostavs/emacs-travis/releases
For reference, here's magit's .travis.yml https://github.com/magit/magit/blob/master/.travis.yml
I'm not sure if the segfault-ing will be completely fixed, however, I've had about 10 successful successive CI runs here
https://github.com/edkolev/evil/commits/ci-experiment
Some notes:
- the CI jobs run for roughly the same time, ~1 min
- this PR adds a check for emacs 25.2 and emacs "master"
- emacs 25.1 is still in the "allow_faulires" group - I've seen it fail …
=> CI: use "emacs-travis" instead of EVM

evil-commands.el
`xterm-mouse-mode' uses control sequences for mouse events which need to be
decoded, otherwise each character in the sequence will be executed as a command.
Fixes #960.
This change came about from [Emacs Bug#29150](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=29150).
=> Decode mouse control sequences

evil-common.el
Refs #952 
This PR addresses these compile warnings:
```
emacs --batch -Q -L . -L lib -f batch-byte-compile evil-common.el
In evil-get-register:
evil-common.el:2012:20:Warning: ‘x-get-selection’ is an obsolete function (as
of 25.1); use ‘gui-get-selection’ instead.
In evil-set-register:
evil-common.el:2100:9:Warning: ‘x-set-selection’ is an obsolete function (as
of 25.1); use ‘gui-set-selection’ instead.
evil-common.el:2102:9:Warning: ‘x-set-selection’ is an obsolete function (as
of 25.1); use ‘gui-set-selection’ instead.
```
I haven't yet figured out how to fix the `find-tag` compile errors.
=> Fix compile warning for deprecated x-set-selection, x-get-selection

evil-commands.el, evil-tests.el
This addresses part of the problem in #969. I'll look at the rest later.
=> Fix detection of newlines in evil-ex-substitute

evil-core.el
Mention the effect of a `nil` state in docstring and give a meaning to using `nil` with `'global` or `'local`.
Handle errors in `evil-define-key` by wrapping definitions in `condition-case-unless-debug`.
=> Some more improvements for evil-define-key

evil-core.el
If the parent keymap already has an auxiliary keymap, ignore it. For example, if the user attempted to bind a key in emacs-lisp-mode-map before this commit, evil-define-key* could define the key in the corresponding auxiliary keymap in lisp-shared-mode-map instead of creating a new auxiliary keymap in emacs-lisp-mode-map. This resulted in keys bound in emacs-lisp-mode-map with evil-define-key potentially being bound in other keymaps that inherit from lisp-shared-mode-map (e.g.
lisp-mode-map).
Addresses #709.
=> Always create new auxiliary map in evil-define-key*

evil-commands.el
This patch makes evil recognize `query-replace-skip-read-only` variable and ignore read only matches while substituting. This is useful in wgrep and wdired mode.
=> Make evil-ex-substitute ignore read only matches.

Makefile, evil-vars.el, evil.el
This is a WIP PR as a result of #992 
I haven't self-tested thoroughly yet. Plus, there's an issue with the generation of `.depend` which is currently worked-around like so:
```elisp
(when evil-want-integration
;; TODO creating the .depend file breaks if the following require is
;; not on a line of its own
(require 'evil-integration)
)
```
Edit: the workaround is is now removed.
Any suggestions for improvements are welcome.
=> Optionally load evil-integration.el

evil-jumps.el
Defer advice until after etags has loaded to prevent a find-tag-noselect was
redefined message.
=> Fix loading of advice for find-tag-noselect

evil-integration.el
Evil's built-in integration with avy is missing some avy commands,
which causes unexpected behaviour: some avy commands do not properly
behave as evil motions.
Add the missing commands, and while at it, sort the names in
alphabetic order.
=> Add missing avy commands in evil-integration

.travis.yml
I've experimented with two CI branches today, in the first one I built the Emacsen from source, the second one happened after I realized all of those segfault started happening after I opted out of VMs when implementing flyspell-related tests. So, I switched back to VMs and this seems to have made a great difference, no segfault so far.  I also took the liberty of reducing the number of builds, the rationale here being that most of them included only minor changes, so the latest one with many changes was chosen.
=> Switch to VM-based CI

evil-ex.el
This PR tries to fix the following issue - calling `evil-ex` non-interactively with initial input `%s/.../...` doesn't show the substitution overlays.
To reproduce the issue I'm trying to fix:
- enter the following in the scratch buffer:
```elisp
;; hello this world
(evil-ex "%s/this/that/")
```
- execute the second line
Without this PR, the substitute overlays aren't displayed -- you don't see what will be replaced.
=> If `evil-ex` is called with initial input, call `evil-ex-update`

evil-commands.el
The current behavior isn't consistent with vim (at least in my tests). It's also
annoying to have point jump to weird locations following an aborted search.
For example, with
`:%s/a/b/c`
If you abort the search with `C-g` before making replacements, point jumps to the
beginning of the region which is the beginning of the buffer in this case. This
is odd, because nothing happened but you lose your place in the buffer.
=> Don't move point following ex-substitute search

evil-commands.el
Do this by simulating the effect of turning on reveal-mode when the substitution
requires confirmation.
Fixes #983
=> Reveal hidden search terms in evil-ex-substitute

evil-test-helpers.el, evil-tests.el
The docstring says there is a race condition if you use `make-temp-name` then
later try to write the file which is exactly what was happening in
`evil-test-write`. I suspect this is the cause of the (random) segfaults in
travis.
Also disentangle the tests in `evil-test-write`.
@wasamasa I looked through old builds and most seemed to be failing around this test, so I think this is the issue with the seg faults. Not to mention that trying to illegally access a file (for whatever reason) along with a race condition fits with random seg faults.
=> Don't use make-temp-name

evil-vars.el
I assume notmuch-tree-mode was introduced some while after https://github.com/emacs-evil/evil/commit/bb2999c12d67d88e254b43c03827c8e8252a391c (i.e. 7 years ago), which was when the other notmuch modes were added to evil-emacs-state-modes.
=> Add notmuch-tree-mode to evil-emacs-state-modes

evil-states.el, evil-tests.el
Previously, the selected text in visual mode was copied to the X
CLIPBOARD, while 'normal' Emacs copies the active region to the
PRIMARY selection (controlled by `select-active-regions`). The latter
is also what the major X toolkits do by default.
This changes evil-visual-update-x-selection to use the PRIMARY
selection and also...
- Uses the wrapper `evil-set-selection` instead of the obsolete
`x-select-text`
- Tests for `display-selections-p` instead of boundness of
`x-select-text` or `ns-initialized`
=> Copy text to PRIMARY, not CLIPBOARD in visual mode

evil-core.el, evil-tests.el
@wasamasa Here's a different version of #984. Changes are
1. I removed the customization variable. I think this is sufficiently correct functionality to make it the default even if it does modify someone's config slightly. 
2. I now teach `evil-initial-state` to look at aliases for modes. This makes a little more sense to me and simplifies the code. 
3. I detect the circular references and print a message as requested. 
Teach evil-initial-state to look at aliases for a mode when they exist and to
handle nil for modes
Note that I still need to add tests for this.
=> Rework #984

evil-commands.el, evil-ex.el
This PR tries to speed up the `:global` ex command. The speedup is roughly 3 times, although I haven't done extensive performance testing.
I've tested `:g/fake/d` on a file with 1k and a file with 10k lines, each line with text `fake`. The results, collected with `elp-instrument-function` on a laptop, are (in seconds):
```
before optimization:
1k lines:  evil-ex-global       3.469728
10k lines: evil-ex-global       34.234797
after optimization:
1k lines:  evil-ex-global     1.6581169999
10k lines: evil-ex-global     11.175745
```
=> evil-ex-global: parse COMMAND only once, not on each matching line

evil-commands.el
This PR fixes the following scenario:
- `make emacs`
- enter in a fresh buffer
```
111
222
333
```
- go to first line
- set mark with `mm`
- using `j`, go to last line
- jump to the `m` mark with
```
`m
```
- you're on the first line now
- hit `C-o` - point should jump back to 3rd line, but it doesn't
As always, please let me know if the PR can be improved.
=> Treat going to marks jumps

evil-common.el
Call `newline`, which respects use-hard-newlines.
This is a (naive initial attempt at a) fix for #1026.
=> Respect use-hard-newlines in evil-insert-newline-{above/below}

evil-core.el
An example use case of making an evil keymap an intercept keymap is to allow a user to reliably give keybindings precedence over any evil keybindings made with `evil-define-key` or `evil-define-minor-mode-key` (e.g. the user uses a non-conventional prefix key that a lot of packages bind by default). Currently, doing this with intercept maps is fairly convoluted. With this commit, it would possible to just do something like this:
```
(define-minor-mode my-intercept-mode ...)
....
(evil-define-key 'normal my-intercept-mode-map
[intercept-state] 'normal
"<high precedence key>" #'binding)
```
=> Allow auxiliary maps to be intercept maps

evil-common.el
Even though `evil-start-undo-step` does check `buffer-undo-list`, it is
possible that the forms wrapped by `evil-with-undo` disable undo in
the meantime. In those conditions, `evil-refresh-undo-step` will
eventually error.
https://github.com/joaotavora/sly/issues/156 references such an
incident.
* evil-common.el (evil-end-undo-step): Also check that
buffer-undo-list is a list here.
=> Better protect against modes that disable undo

evil-jumps.el
Previously, it would always push the current position.
=> Fix evil-set-jump called with an argument

evil-vars.el
This PR improves vdiff folding integration - vdiff is moved higher in`evil-fold-list`, making it take precedence over other folding modes. This makes sense because a user might have "long-lived" modes such as outline-mode/origami-mode always enabled and occasionally use vdiff which is a "short-lived" mode - there's no point in keeping vdiff enabled all the time. As a result, when the user is vdiff-ing a buffer which also happens to have outline-mode on, `zo` will open folds using vdiff instead of outline.
This PR also adds vdiff-3way-mode to `evil-fold-list`.
Refs https://github.com/emacs-evil/evil-collection/pull/179
=> Refine vdiff folding

evil-ex.el
Fixes #1079, see that issue for a detailed explanation of the problem. Instead of adding `evil-ex-teardown` to the global value of `minibuffer-exit-hook`, it is added to the local value of that hook in the Ex minibuffer so that it is called in the right minibuffer when recursive minibuffers are enabled.
=> Support recursive minibuffers in Ex

evil-commands.el, evil-tests.el
Steps to reproduce the problem: 
1. paste to the scratch buffer 'Sample text' 
2. press `0veA11` 
3. text in the buffer: Sample 11text
Expected result: Sample11 text
=> Fix for append from visual state

evil-maps.el
This prevents evil-replace from inserting a literal C-g if C-g is typed after
entering replace state.
=> Allow C-g to abort evil-read-key

evil-commands.el, evil-vars.el
The following commands now act on visual lines when
`evil-respect-visual-line-mode` is non-nil:
`evil-insert-line`
`evil-append-line`
`evil-find-char`
`evil-find-char-backward`
`evil-find-char-to`
`evil-find-char-to-backward`
=> Teach more commands about evil-respect-visual-line-mode

evil-common.el
Windows created specifically to hold evil-list-view-mode buffers seem a lot like
other temporary windows in Emacs, e.g. the ones created by describe-function.
These tend to define q to mean quit-window, rather than kill-this-buffer; The
quit-window command has the nice property that if a window was created to hold
the buffer in question, that window will be deleted – but if an existing window
was repurposed to hold the buffer, the effect is the same as bury-buffer.
Note that this is also in line with the default behaviour of Vim, where pressing
q in the marks list restores the previous window layout.
=> Delete window on q if created to hold evil-list-view-mode buffer

evil-commands.el, evil-common.el, evil-macros.el, evil-search.el, evil-states.el, evil-tests.el
The docstring of evil-cursor-back only mentions that it applies to moving the
cursor back when exiting insert state, but in many cases it was tied to also
moving the cursor when reaching the end of the line. We have
evil-move-beyond-eol to control that behavior, and there doesn't seem to be a
good reason that the two must be tied together.
Fixes #1178
=> Unwed evil-move-beyond-eol and evil-move-cursor-back

evil-commands.el, evil-integration.el, evil-macros.el, evil-states.el, evil-types.el, evil-vars.el
when evil-respect-visual-line-mode is non-nil, including
evil-change-line, evil-delete-line, and evil-yank-line. Most of the work is done
through the motions evil-line-or-visual-line and
evil-end-of-line-or-visual-line. These motions use visual lines when
visual-line-mode and evil-respect-visual-line-mode are non-nil, and revert back
to standard lines otherwise.
Visual selection via visual lines in the sense of visual-line-mode is supported
by adding a new screen-line type (named to avoid confusion with visual state).
=> Make more commands support visual-line-mode

.gitignore, .travis.yml, evil-tests.el
It's not been a very well kept secret that CI has been absolutely useless. Hopefully this fixes most of the issues.
The main reason for the problems is that we've been using `ert-run-tests-batch-and-exit`, which apparently in Emacs 26 and later raises an error outside of batch mode. This just leaves the test scripts for those versions to hang for ever, waiting for Emacs to exit.
We'd prefer not to use batch mode because we have tests that use Emacs functionality not available there (like windows).
Instead I've modified the test script to mimic the behaviour of batch mode, to run the tests interactively instead and then exit emacs with an appropriate return code.
Since the test results are very difficult to read in the travis log, I've instead chosen to hide them entirely by wrapping the …
=> Redo travis setup

README.md
Full repository is 43MB as of now, shallow copy with only the latest commit is 2.9MB.
Majority of people who clone the repository through the README.md do so for the purpose of using evil, not modifying it. There's no need to make them download the whole repository.
=> Clone shallow repository in README.md#download

evil-ex.el
Previously when a current line prefix was specified (i.e.
giving a numeric argument of 1 before calling `evil-ex`),
Ex attempted to `concat` together a string wrapped in a
list with `evil-ex-initial-input`, but if `concat` is
passed a list it expects it to be a list of characters not
strings.
=> Fix `evil-ex` called with a current line prefix

evil-commands.el
See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31546
This hasn't been accepted into emacs yet. It's probably worth waiting until the
final version of the patch is applied.
=> Prevent errant scroll on mouse click

evil-common.el
Docstring says that the spec can be a zero-argument function, but
evil-set-cursor incorrectly handles such a function like a list preventing the
function from being executed.
=> Fix evil-set-cursor when spec is a function

evil-integration.el
With the recent code changes, motion `0` was broken, because the command name used is not the one that is defined.
=> Fix evil motion 0 binding command

evil-commands.el
Some more advanced backends require this to work. See #1099
=> xref: get identifier from backend instead of getting it ourselves

evil-core.el
Hi @TheBB, thanks for taking this over. I had this idea to make "leader" keys more familiar to vim users. @noctuid let me know what you think too. I think the idea is straightforward and gets to similar syntax to vim. Not a lot of code either :)
Add `evil-send-leader` and `evil-send-localleader` which will push the symbol
<leader> or <localleader> into the `unread-command-events` list. This allows one
to bind a key to `evil-send-leader` to make it a leader key and activate bindings
like the following.
```elisp
(defun hi ()
(interactive)
(message "hi"))
(define-key evil-normal-state-map (kbd "<leader> h") 'hi)
```
For convenience, evil-set-leader can be used as follows
```elisp
(evil-set-leader 'normal (kbd "C-c"))
```
An optional argument makes it a localleader.
=> evil-core.el: Add <leader> functionality

evil-commands.el, evil-common.el
When header line is enabled, `evil-scroll-up` and `evil-scroll-down` won't remain in the same position when scroll.
```
From my investigation, the root cause was as follows.
On Emacs 24 with non-nil header-line-format, y offset returned by 
`posn-at-point' is relative to the text area not including the header line.  
However, `posn-at-x-y' takes y offset relative to the buffer area including the 
header line.
Before Emacs 24, both of `posn-at-point' and `posn-at-x-y' are relative to the 
buffer area including the header line.
```
Original comment by `yukishi...@google.com` on 1 Nov 2013 at 3:06
- Changed state: **Started**
_Originally posted by @GoogleCodeExporter in https://github.com/google/mozc/issues/196#issuecomment-95066744_
Fix #713. Fix #965. Fix #1063. Close #1080.
=> Fix behavior of evil-scroll-up and evil-scroll-down

Cask, evil-command-window.el, evil-commands.el, evil-common.el, evil-core.el, evil-development.el, evil-digraphs.el, evil-ex.el, evil-integration.el, evil-jumps.el, evil-keybindings.el, evil-macros.el, evil-maps.el, evil-pkg.el, evil-repeat.el, evil-search.el, evil-states.el, evil-test-helpers.el, evil-tests.el, evil-types.el, evil-vars.el, evil.el
1.2.15 was accidentally tagged as 1.12.15, which was picked up and released by MELPA Stable.  So to be able to release new stable versions I guess it's easiest to just say that we're on 1.12 now.
=> Release 1.12.16 (Oops)

evil-commands.el, evil-maps.el, evil-tests.el, evil-vars.el
Add an option `evil-want-C-u-delete` to allow <kbd>C-u</kbd> to delete back to the indentation in Insert state, but disabled by default.
It behaviors just like `evil-delete-backward-word`:
Before (cursor on "h")
```
abc
def g[h]i
```
After press <kbd>C-u</kbd> once in Insert state:
```
abc
[h]i
```
Press <kbd>C-u</kbd> again
```
abc
[h]i
```
=> Add evil-want-C-u-delete option

evil-search.el
Do not perform the second search if the original search bound was set, as it must necessarily be bypassed.
Use the original starting point for the search as the bound for the second search.
Fixes #843 and supersedes #1070.
=> Fix bounds of wrapped search

evil-integration.el, evil-tests.el, evil-vars.el
If `evil-want-abbrev-expand-on-insert-exit` is non-nil, abbrevs are always expanded when exiting insert state, regardless of whether `abbrev-mode` is enabled. This respects the setting of `abbrev-mode`, and also allows setting the variable post-load or buffer-locally.
Fixes #1175
=> Expand abbrevs after insert state only if abbrev-mode is enabled

evil-vars.el
- Remove some obsolete modes from default Emacs state
- Don't start `git-commit-mode` in Emacs state (see discussion in #1145, evil-magit sets it to the default state so this feels like a sensible default)
cc @justbur
Fix #1145
=> Remove some emacs state modes

evil-commands.el
This enables use of e.g. C-u p to paste four times.
Fixes #1199
=> Fix numeric argument for paste commands

evil-commands.el
Commands like `evil-window-rotate-upwards` and `evil-window-move-very-top` only
consider the buffer in each window when manipulating the window tree, but if a
window has specific window properties that need to be maintained (like those in
`window-persistent-parameters`) that information is lost.
Refactor the window manipulation commands to use `window-state-get` and
`window-state-put` to retrieved and restore the state of the window tree so
that window properties in each window are maintained.
Also integrate the window manipulation commands with side windows, i.e. windows
with a non-nil `window-side` window parameter, by only manipulating the part of
the window tree that are not side windows.
* Add the macro `evil-save-side-windows` which removes all side windows on
entering the macro …
=> Better integration of window manipulation commands

evil-tests.el
This PR does the following:
- tests related to the command window are skipped when emacs is run in batch mode
The cmd window tests always fail with something like "error resizing window". With this change these tests will be skipped in batch mode.
As to why I run evil's tests in batch mode - long story short, I'm switching [evil-goggles](https://github.com/edkolev/evil-goggles) to [makel](https://gitea.petton.fr/DamienCassou/makel). In addition to evil-goggles's own tests, I run the whole evil-tests.el suite with the evil-goggles mode on. Since makel runs the tests in batch mode, the evil tests suite always fails for me.
=> Skip command window tests when run in batch mode

evil-common.el
The PR #1154 is supposed to fix the issue about evil-scroll-up
and evil-scroll-down. It works nicely in most scenarios.
However, when the header line is really tall,
evil-header-line-height will give an incorrect result,
making the bug that is supposed to be fixed by the mentioned PR
reappear again.
This PR switches evil-header-line-height to Emacs' built-in
window-header-line-height which corrects the mistake.
=> Fix behavior of evil-scroll-up and evil-scroll-down again

evil-common.el
When setting a new global map, the tab-bar entry must be copied to the new map from the old one to avoid hiding the tab bar.
Fixes #1245.
* `evil-common.el` (`evil-read-key`): Preserve the `tab-bar` entry from the old global map.
=> Preserve the tab-bar in `evil-read-key'

evil-core.el, evil-integration.el, evil-test-helpers.el, lib/undo-tree.el
This brings us closer to the ideal that loading files should be side-effect-free. The evil-integration file is a sinner.
This moves the undo-tree-mode activation from top-level to being conditioned on the enabling of evil-mode.
Will make #1229 nicer.
=> Enable undo-tree-mode only when evil-mode is turned on

evil-core.el, evil-integration.el, evil-test-helpers.el, lib/undo-tree.el
Reverts emacs-evil/evil#1248
I've since discovered that the newest undo-tree seems to have some problems on Emacs 27.
Also I'm thinking maybe the automatic enabling of undo-tree-mode should remain dependent on evil-want-integration as it is now, so it should stay in the evil-integration file.
Sorry for jumping the shark on this.
=> Revert "Enable undo-tree-mode only when evil-mode is turned on"

evil-search.el
This PR reverts #1221 and introduces another fix for #843 without the regression of #1233.
The source of #843 is that isearch calls our search function, which may find a match that is filtered out, usually because the text is invisible. In that case isearch calls the search function again, until it either returns nil (no match found) or finds a match that isn't filtered.
If we wrap the search around the buffer endpoints and all matches are filtered out, this will cause an endless loop experienced by the user as Emacs freezing.
#1221 fixed this by modifying the bounds of the wrapped search, preventing it from finding the same match endlessly, but this introduces its own problems: some matches that should be found are now no longer found. This PR reverts that fix.
The original problem is …
=> Honor isearch filter predicates

evil-commands.el, evil-tests.el
Reverts part of 1d6ba80.
Fixes #1253.
=> Call delete-backward-char interactively again

evil-search.el
In some cases search is triggered not from the minibuffer, in which case `minibuffer-selected-window` will not accurately capture the window in which search highlights should be created.
=> Ex search highlights: use selected window as fallback

evil-command-window.el, evil-commands.el, evil-common.el, evil-core.el, evil-development.el, evil-digraphs.el, evil-ex.el, evil-integration.el, evil-jumps.el, evil-keybindings.el, evil-macros.el, evil-maps.el, evil-repeat.el, evil-search.el, evil-states.el, evil-test-helpers.el, evil-types.el, evil-vars.el
In the evil library itself there was only one change I had to do. The ex parser used some let-defined functions to deal with the 'dollar sign' forms in `evil-ex-grammar`. Once I converted them to properly named functions, all tests pass with lexical binding.
Unfortunately, some functions and macros in evil don't play well with lexical binding, so I left the test file itself alone for now. As far as I can tell, these are:
- `evil-define-key`: this is actually a macro which if given an unquoted symbol for the keymap first checks if it's bound, then binds the key if it is, or delays the binding if it isn't. This is a neat feature designed to avoid having users worry about `eval-after-load`, but unfortunately it just doesn't work with lexical binding and I don't see any way that it can do so …
=> Enable lexical binding

evil-ex.el, evil-maps.el, evil-search.el
Open apropriate command windows for Ctrl-f while in minibuffer for an ex command
or a search. As all ways to abort a minibuffer do not return and restore the
active buffer, we have to set the content of the minibuffer and exit normally to
trigger the apropriate action. Also restoring the window configuration is
necessary so minibuffer-selected-window is not changed.
This pull request should resolve issue #1147
=> Implement Vim Ctrl-f in minibuffer.

evil-commands.el
It's better to unify the way between `evil-paste-*` and `yank*` to handle with universal argument, so spacemacs can do extra hook to them.
Refer: syl20bnr/spacemacs#13161
=> Change the way to get universal argument

evil-common.el
Correct typo (COMPOUNT->COMPOUND) in symbol name in window server selection data-type list.
Should correspond with the symbol used [in the emacs source code](https://github.com/emacs-mirror/emacs/blob/master/lisp/select.el#L306) and [in the emacs ipc encoding documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Communication-Coding.html).
=> Correct typo (COMPOUNT->COMPOUND) in symbol name

Makefile
Useful to have a specific info target when some Emacs package installers
expect this target (such as el-get).
=> Makefile: add 'info' target

evil-core.el
fix evil-define-state :exit-hook typo
=> fix evil-define-state :exit-hook typo

evil-common.el
At the moment, having `&rest` in a command's argument list results in the following error when running the command:
```
Symbol's value as variable is void: &rest
```
=> Don't pass &rest to ignore in evil-define-command

evil-command-window.el
- evil-ex-command-window only accepts 0 arguments
- and it doesn't make sense to call itself recursively
- this issue was introduced in [1: 48ceb43]
1: 48ceb43f8a1e95e6d7eafe428ff640d83952462f
Clean up compilation warnings from lexical binding
=> fix `wrong number of argument error` in evil-ex-command-window

evil-vars.el
The following variables aren't set by their `:set` functions.
This results in void variables(#1278). This commit will fix it.
* `evil-want-Y-yank-to-eol`
* `evil-disable-insert-state-bindings`
* `evil-overriding-maps`
* `evil-intercept-maps`
=> Fix: some `evil-custom-` variables are void

evil-commands.el
It seems that `xref-find-definitions` returns `nil` on success, at least on Emacs 26.3.  This means that the `run-hook-with-args-until-success` call in `evil-goto-definition` will call the next search function even if `xref` is successful.
This PR makes `evil-goto-definition-xref` return `t` as long as there's no `user-error` raised (i.e. `xref` didn't fail to find a match).  ~I also added `(require 'xref)` to `evil-commands.el`, since I get an error with the below steps without it.~
1. Run Emacs with `make emacs` using Evil's Makefile.
2. Evaluate the following, since `evil-goto-definition-imenu` will succeed:
``` emacs-lisp
(require 'xref)  ; "Symbol’s function definition is void: xref-backend-identifier-at-point"
(setq evil-goto-definition-functions '(evil-goto-definition-xref …
```
=> Make evil-goto-definition-xref return non-nil on success

doc/Makefile
When sphinx is not found, make clean (and others) will fail. This
change prevents running sphinx if sphinx-build binary is not found.
Here is used 'command' instead of 'which', for checking presence of
binary in PATH, to make it more portable across shells and unixes.
=> Fixed make clean and doc build

evil-commands.el, evil-tests.el
The `kill-ring` let binding in `evil-visual-paste` meant that
`evil-get-register`'s view of `kill-ring` (used in `evil-paste-before`
and `evil-paste-after`) was limited to only entry `0` (and whatever
`evil-delete` may have added to rebound `kill-ring`). Therefore,
registers >1 were not actually visible to functions that needed
them. Condensing the `let*` binding so `kill-ring-yank-pointer` is
bound directly to `(list (current-kill 0))` was chosen as a simple and
effective method to fix the bug.
Fix for issue #1295
=> Fix issue 1295: failed visual-paste from registers >1

evil-common.el
Text objects for tags didn't work as expected when tag has attribute (or just closing angle brackets) in next line.
For example, try to select (type `vat` in normal mode) this tag:
```xml
<foo
>
</foo>
```
Or this:
```xml
<foo
someAttribute="value"
>
</foo>
```
=> Fix multiline tag text object.

evil-commands.el, evil-common.el
* `evil-commands.el` (`evil-visual-paste`): Delete declaration of the `new-kill` variable to silence the byte compiler.  The variable is unused since https://github.com/emacs-evil/evil/pull/1296.
* `evil-common.el` (`evil-add-to-alist`): Use `with-no-warnings` around the recursive obsolete function call to silence the byte compiler.
=> Silence byte compiler warnings

evil-ex.el
The latest Emacs 28 requires this.
=> Add version to `define-obsolete-function-alias' invocation

doc/source/faq.rst
Add reference to the `o` key in the default text objects keymap, as an alternative to `w` in some cases.
Closes #1388.
=> Expand FAQ discussion of word vs. symbol text objects

evil-core.el
While chatting with @angrybacon we realized that `evil-define-key*` was missing the `(declare (indent defun))` which prevents it from being indented the same as `evil-define-key`.  This PR adds the expected declaration to get that indentation behavior.
=> Add missing indent declaration to evil-define-key*

evil-commands.el
Without this, `.` will repeat undo, at least when using undo-tree.
=> Abort repeat with evil-undo

evil-commands.el, evil-tests.el
=> Fix visual paste from `=` register by memoizing `evil-get-register`

evil-commands.el, evil-maps.el, evil-tests.el
Adds `evil-find-file-at-point-visual` for finding a file using the
selected visual region. (See `:h v_gf` in Vim)
Adds tests for "gf" in both normal and visual modes.
=> Add "gf" to visual mode

evil-vars.el
Normal state's bindings don't work there by default. (And maybe) It's
not worthy for evil-collection to define them.
=> Add bs-mode to evil-emacs-state-modes.

evil-common.el
Fixes what looks like a mistake in `evil-get-register` where no errors were ever thrown. Looks like it breaks evil-owl, so won't merge until evil-owl can handle (or, most likely, ignore) the errors.
=> use `noerror` properly in `evil-get-register`

evil-commands.el, evil-repeat.el, evil-tests.el
`evil-repeat` is currently broken when in the temporary normal state reached from `evil-execute-in-normal-state`. This PR fixes that.
=> Repeat when execute in normal state

doc/source/faq.rst
For me, the Evil default of using words instead of symbols is
only really important for `#` and `*` searches. The fix for them
is much simpler than for the other motions after
https://github.com/emacs-evil/evil/issues/360 (thanks!).
Ideally, these variables would be documented elsewhere
as well. I'm not sure if I'll get around to it.
=> Add info about  `evil-symbol-word-search` to FAQ.

evil-commands.el, evil-tests.el
Previously, with the cursor on an empty line `evil-find-char` would continue searching on the next line. This was because `forward-char` would advance to the next line, after which the `search-forward` bound would be wrongly calculated.
=> Fix evil-find-char on empty line

evil-core.el
In `evil-get-auxilliary-keymap`, there's already a check on `state` when entering the function.
Should `state` be `nil`, it won't enter the `let*` form.
The binding specification
`(aux (if state (lookup-key map key) map))`
always reduces to
`(aux (lookup-key map key))`
And `(parent-aux (when (and ignore-parent (keymap-parent map) state)))`
always reduces to
`(parent-aux (when (and ignorant-parent (keymap-parent map))))`
This commit removed unnecessary `if` form, and removed redundant `state` in `and` form, as described above.
=> evil-core: refactored  `evil-get-auxiliary-keymap`

evil-common.el
Some packages such as evil-cleverparens depend on `evil-yank-rectangle` always returning the text. `kill-new` only does this if the `interprogram-cut-function` does, which isn't guaranteed.
=> Always return text from evil-yank-rectangle

evil-vars.el
It's more intuitive for evil beginners if no keymap overriding evil maps.
=> evil-vars: reset evil-overriding-maps to an empty list

evil-commands.el, evil-common.el
=> Scroll half of the visible screen respecting zoom level

evil-commands.el, evil-tests.el
Interestingly, this isn't necessary in emacs 25 and earlier. Hence the `unless` test. I'm not sure if this is a bug introduced after emacs 25.
=> Add [return] to evil-repeat-info when recording for evil-ex-search

evil-search.el, evil-tests.el
Disable `evil-ex-search-vim-style-regexp` when building the pattern for `evil-ex-search-word-forward`. We don't want the pattern transformed because it is not being entered by the user. Closes #347
=> Fix evil-ex-search-word-forward with evil-ex-search-vim-style-regexp

evil-search.el
When using the search module: `evil-search`
And a search prompt is opened: `/` or `?`
If a window is mouse selected, then the search prompt remains active in the minibuffer.
Now when single pressing a operator key: `c`, `d`, `y`
then it behaves as if it was double pressed: `cc`, `dd`, `yy`
meaning that it acts on the current line.
---
- Switch to the `*scratch*` buffer
- Type:
```
a
b
c
d
```
- Enable the search module: `evil-search`
by evaluating: `S-M-;`
```elisp
(evil-select-search-module 'evil-search-module 'evil-search)
```
- Open a search prompt with: `/` or `?`
- Without closing the prompt, mouse select another window.
The search prompt remains active,
but now some evil bindings don't work as expected:
- `c` works as `cc` which deletes the line and enters insert state.
- `d` works …
=> Exit search prompt on mouse leave minibuffer

evil-search.el, evil-vars.el
I tend to miss when `evil-search` wraps around the buffer. Ringing the bell combined with `visible-bell` makes it much more obvious to me than just the text in the echo area.
`isearch` also rings the bell when it wraps.
=> Add `evil-search-wrap-ring-bell` customization variable

doc/docstringdb.json, evil-states.el, evil-vars.el
Vim user can select a region in visual mode and press the key `p` to
replace the selected text.
But in GUI Emacs, the selected text won't be replaced because the commands
in visual state automatically insert the selected text into the X selection.
Press key `p` or run `evil-paste-after` only copies from the X selection which
is same as the selected text.
Console Emacs does not have this problem.
=> Add option of stop updating X PRIMARY selection with the current visual region

evil-common.el, evil-integration.el, evil-vars.el
This PR improves on #1519, which I made about a week ago. I'm pretty new to Emacs development, so when I made those changes I was imagining some graybeard poweruser with way more experience than me, willfully rebinding digit keys besides "0" to bizarre functions. However, after some reflection I imagine that this is such a rare use case that it isn't really necessary to support it. By way of explanation:
In Vim/Evil, we know that if "0" is the first number we see in a sequence, we should treat it as a motion, because e.g. "d010j" is meaningless - you could just write "d10j". There will never be a case where "0" is *both* the first digit in a sequence *and* has meaning as a number, so when we see a "0" at the beginning of a sequence we're always safe to treat it as a motion instead of part …
=> Fix #1518: "custom functions bound to '0' break motion parsing" in a saner way

evil-commands.el
Sorry, but this is the same as #1064.
#1064 was forked from a very old code, so I opened a new pull request while updating it, so please take a look.
This allows kmacro to edit macros independently of the original evil macro.
Update is,
1. Add the same macro recorded as `evil-record-macro` to the kmacro ring.
2. Make the added kmacro editable
This simply adds the same macro to the kmacro ring and allows the user to edit it(without touching original evil macro). So I believe this update will not break the workflow for existing evil users.
Thank you.
=> Make `evil-record-macro' add the same macro to the kmacro ring

evil-commands.el, evil-tests.el
Add support for the `<filename>:<line>:<column>` format. Previously, given this format, `column` was treated as line number and `line` was ignored.
=> evil-find-file-at-point-with-line | support column number too

evil-common.el, evil-tests.el
=> Allow parsing of js arrow fn `=>` in xml tags

evil-vars.el
* evil-vars.el (evil-markers-alist): Adjust to new name
=> Fix beginning/end-of-current-sentence marker

evil-commands.el
regression introduced in #1554
=> Use `end-kbd-macro` to fix regression clearing registers

evil-commands.el
See issue https://github.com/emacs-evil/evil/issues/1585
* evil-commands.el (evil-fold-action): add FORMAT argument which is now required as of Emacs commit d52c929e31f60ff0462371bfe27ebd479e3e82bd.
=> evil-fold-action: add missing FORMAT argument to with-demoted-errors

evil-search.el, evil-tests.el
If very magic is enabled, the `"\\_<pattern\\_>"` will be transformed into `"\\_\\<pattern\\_\\>"`:
Minimal configuration to reproduce:
```elisp
emacs -Q -L ~/repos/emacs-evil --eval "
(progn
(toggle-debug-on-error)
(require 'evil)
(setq evil-magic 'very-magic)
(setq evil-ex-search-vim-style-regexp t)
(evil-select-search-module 'evil-search-module 'evil-search)
(evil-mode 1)
(with-current-buffer \"*scratch*\"
(erase-buffer)
(insert \"foo bar\nfoo bar\nfoo bar\nfoo bar\nfoo bar\nfoo bar\n\")
(insert \"\nReproduce: \n\n  Press / and RET to repeat the last search.\")
(goto-char (point-min))
(evil-ex-start-word-search nil 'forward 1 t)
(evil-ex-nohighlight)))
" -nw
```
=> evil-ex-make-pattern: Don't transform the word boundaries into vim-style

evil-commands.el
This fixes window splitting which did not work properly when using a
count (ex: "3C-w n") or providing a file (ex: ":vnew ~/.emacs").
=> Make window commands consistent with VIM

doc/source/settings.rst, evil-search.el, evil-vars.el
This adds non-incremental search capability to evil, similar to vim/neovim's "set noincsearch" option.  Only needs a few lines of code change.
It adds a custom var ```evil-ex-search-incremental``` which defaults to t, but can be set to nil to activate non-incremental search (only if ```evil-search``` module is used.)
Fixes #1304.
=> Add option for non-incremental search (#1304)

evil-vars.el
`haskell-interactive-mode` and `utop-mode` are REPL-like modes that both
inherit from `fundamental-mode`, so they need to be explicitly listed here.
=> evil-vars: Update evil-insert-state-modes

evil-commands.el, evil-tests.el
=> Exclude final empty line from implicit inclusion in substitution

evil-maps.el
C-h is behaving as C-u behaves, seemed like a simple typo; behaves as expected after a couple days of use.
=> fix C-h behavior when evil-want-C-h-delete is non-nil

evil-commands.el, evil-common.el, evil-tests.el
Revert `forward-evil-word` changes and new objects, in favour of a "restricted" form of `evil-select-inner-object`
=> New object approach

evil-tests.el
A small typo in the tags for a test. Changes `jums` to `jumps`.
=> Fix typo in test tags

evil-ex.el
Add auto-completion for `evil-ex` LISP expressions leveraging
`elisp-completion-at-point` if available.
When executing an Elisp expression with `:(`, there should be auto-completion for lisp functions instead of a "wrong number of arguments" error. Implement that.
=> `evil-ex': `eval-expression' auto-completion

evil-tests.el
When there's outdate byte-compiled files, they may be loaded instead
of the new changed code.
Enable `load-prefer-newer` would avoid this.
=> Make sure not to test stale code

evil-vars.el
aa3ea1dcfc54fe25581841a8685679d482e99b3f unwed these, but they should
still keep in touch (so people can easily find out why behaviour
changed).
=> Mention evil-move-beyond-eol in docstring of evil-move-cursor-back

evil-common.el, evil-tests.el
Cope with non-string register contents. Fixes #730
=> Fix for issue #730 appending to macro fails

evil-common.el
Fixes https://github.com/emacs-evil/evil/issues/1297
This is mostly a workaround for `temporary-goal-column` occasionally having negative values when both `whitespace-mode` and `display-line-numbers-mode` are enable. Without this change, `evil-ensure-column` would sometimes pass in negative values to `line-move-to-column` resulting in "line-move-to-column: Wrong type argument: wholenump, -5" errors.
=> Prevent setting a negative value for `temporary-goal-column`

evil-commands.el
Closes #1624 
This PR updates `evil-quit` to properly handle tabs.
I think `tab-bar-close-tab` woud have been introduced in emacs 27, while evil supports emacs back to version 24. However, in this case we are already handling errors so this solution is still compatible with those versions. I couldn't come up with a clean way to use an `fboundp` here, and given it isn't strictly needed I omitted it, but I'm happy to take suggestions if there is a cleaner way to accomplish this.
=> update evil-quit to handle tabs

evil-command-window.el
No more "There are no full lines in the region" when the history is empty, and it is actually a small optimization since reverting lists is faster than reverting lines in a buffer.
=> Small fix in 'evil-command-window-ex

evil-commands.el, evil-common.el
Before commit
04b25f6 Add `evil-select-inner-unrestricted-object`
evil-select-inner-object was used for unrestricted selection. 04b25f6
made this function restrict selection to a line, and introduced a new
function evil-select-inner-unrestricted-object that works same way as
evil-select-inner-object before.
But evil-select-inner-object is an API that might be used by people in
custom configuration, and changing behavior of the function would result
in silent breakage.
It is also worth noting that documentation at doc/source/extension.rst
and doc/build/texinfo/evil.texi still mentions the older unrestricted
behavior.
So let's restore the original behavior of evil-select-inner-object by:
1. Renaming evil-select-inner-object → evil-select-inner-restricted-object
2. Renaming …
=> Restore `evil-select-inner-object` API

evil-common.el, evil-tests.el
It's useful to set the marks (`<` and `>`) to change what the `gv` command selects.
Fixes #1634
Vim supports it: [:help m<](https://vimhelp.org/motion.txt.html#m%3C)
=> Allow setting selected visual area marks

evil-common.el, evil-tests.el
In vim, deleting an indented word when it's the only word on a line
will just not delete any whitespace.  This applies specifically to
word objects in vim (see
https://github.com/vim/vim/blob/c7bd2f08e531f08723cdc677212a3633d11c9a97/src/textobject.c#L809),
and not any other objects.
=> Fix daw deleting indentation when deleting the only word in a line

evil-states.el, evil-tests.el
=> Clear `evil-this-register` when leaving visual state

evil-common.el, evil-tests.el
=> Save excursion when adding preceeding whitespace to A word

evil-commands.el, evil-vars.el
This is pretty new in Vim (Jan 2022)
=> Never kill on visual paste when using evil-paste-before

evil-commands.el, evil-maps.el
Fixes #1639
Preferred to add an evil function and keep goto-chg as it is.
=> Add `evil-goto-last-change` & reverse, taking count arg

evil-states.el
With composed characters in the buffer, such as with prettify-symbol-mode
active, emacs may adjust point after the post-command-hook is run. In this case,
evils visual markers do not get updated prior to say evil-delete and the deleted
region does not agree with what is seen visually (only part of the composed
characters are deleted). Forcing a last update using evil-visual-refresh
in evil-visual-range resolves this issue.
=> Make sure visual markers are up to date in evil-visual-range

evil-core.el
My understanding is that Evil activates `evil-local-mode` as early as possible, but there is no guarantee that it is able to do so before the buffer's input method is set. Unfortunately, the current `evil-local-mode` just discards the buffer's old input method, so the order of these two actions is significant.
As a minimal example, evaluate the following and inspect the resulting buffer:
```elisp
(with-current-buffer (get-buffer-create "no-german-postfix")
;;(evil-local-mode)
(activate-input-method "german-postfix"))
```
No matter the Evil state, the input method is no longer set. In this example, the issue can be worked around by uncommenting the second line, but typically you'd have to modify other people's code. In my case, I noticed it with `rcirc` channel buffers which were missing …
=> Keep using the old input method in `evil-local-mode`

Makefile
Hi, I'm using FreeBSD, which has BSD `sed` program, not GNU `sed` . So in my environment `Makefile` doesn't work especially at line 5.
It's great if I could pass actual sed program to use like `SED=gsed make` (especially when installing via package manager like `el-get`) . So I made it variable. 
I think this change doesn't break current behavior.
=> Compatibility: use $SED instead of sed

evil-common.el
I found that on Emacs v29, `" + p` does not paste from the system clipboard if the clipboard was populated outside emacs, rather it pastes from the kill ring.
It looks like this same bug briefly existed in the built-in `gui-selection-value` until it was fixed in [this commit](https://github.com/emacs-mirror/emacs/commit/2289fafeaf) by checking a new var `gui--last-cut-in-clipboard`.
It also looks like `gui--selection-value-internal` (previously `x-selection-value-internal`) has drifted from the evil code that's based on it.  Rather than attempt to bring the evil code up to date while keeping compatibility with Emacs 24, I opted for a version check so we can just call `gui--selection-value-internal` if it exists.
It's unclear to me why this code was duplicated in evil in the first place. …
=> Fix pasting from ?+ register in Emacs 29

evil-commands.el, evil-common.el, evil-tests.el
In modern versions of Vim (and Neovim), doing an action on something in parens will jump to the next instance of those parens and perform the action on them if you're not in those parens.
For example, if you are on the line `int main(int argc, char **argv) {` and type `0cib`, it will change everything inside the parens even though you initially went to the beginning of the line. This pull request adds this functionality.
This feature already works on strings.
One bug is that if you yank something in parens and it needs to jump to the next pair because you're not in parens, in Vim it moves your cursor to the beginning of the next pair, while here it doesn't move your cursor. I couldn't figure out how to fix this.
=> evil-select-parens selects next pair if not in parens

evil-common.el, evil-tests.el
This pull request does not have the issue that #1470 had: The workaround is only applied at the boundaries of logical and visual line movements, which were the only places where things went awry.
I removed support for `next-line-add-newlines`, almost feel like it would be better to add that code to the `evil-next-line` and `evil-next-visual-line` functions. In any case, it feels wrong to have `evil-line-move` call `next-line`/`previous-line`.
No tests yet, maybe someone could help out with that?
Resolves #1469
=> Fix logical/visual line move followed by the other

evil-commands.el
Reverts commit bbe92d1 (Handle scroll margin in scroll-to-top/bottom functions (re #618), 2016-03-31) which introduced a bug in evil-scroll-bottom-line-to-top (due to recenter argument becoming negative with scroll-margin set to 0.) recenter itself has clamped to scroll_margin for at least 18 years now, so it is unclear why that commit was even necessary.
Also fixes the docstring for evil-scroll-top-line-to-bottom and avoids scanning down from (point-min) to the line the point is already at.
=> Fix up the cmds that scroll relative to cursor

evil-common.el
Hi,
I noticed after the merge of #1673 that I didn't take into account the case in which the open parens are a string. In that
case the condition always gives false and it keeps looping, because I compared only with the first char. Also didn't account for the case in which we are at the `eob`, where `char-after` gives `nil`, resulting in an unfriendly error message.
In this fixup `char-after` is replaced by `looking-at-p`, leveraging the same regexp string used afterwards.  I thought to 
add a `regexp-quote` call to that, in case the open delimiter has special chars, but noticed that in case of string 
delimiters, they are already assumed to be correct regexps by the inner function `evil-up-block`.
E.g. before the fix:
`|prova <~`
`(evil-select-paren "<~" "~>" (point) (point) 'inclusive …
=> Fixup evil-select-paren #1673 for multichars delimiters

evil-common.el, evil-tests.el
Hi,
sorry for the scattered PRs, but i figured out a bug on a very common use case, that is jumping to next bracket.
When the open delimiter is a single character which has special behavior in regexps, the call `(string open)` gives the
char not escaped, and the following functions that use such regexp fail.
It causes the common case of commands on `evil-a/inner-bracket` textobjects to fail, for instance:
`|prova di [testo]`
`ci[`
gives evil-motion-range: Invalid regexp: "Unmatched [ or [^"
Now that should be fine, thanks for your consideration.
=> Fix evil-select-paren #1673 for regexp special chars

evil-vars.el
Fixes #1416 and removes make-variable-buffer-local from other variables since it's generally not correct to use this function for user-options. It should be set by individual users who want this behavior.
=> Remove make-variable-buffer-local from variables (fixes #1416)

evil-states.el, evil-tests.el
This reverts commit 7133220.
@justbur see my message in https://github.com/emacs-evil/evil/pull/1655 - I'm reverting this, but please feel free to make a PR to re-add the functionality you want without breaking the new test.
=> Revert "Make sure visual markers are up to date in evil-visual-range"

evil-commands.el, evil-common.el, evil-macros.el, evil-states.el, evil-tests.el, evil-types.el
In `evil-ensure-column` there is no point in normalizing `temporary-goal-column` a second time after BODY, since that variable is used to store the saved column that must not be overwritten. Also tracking EOL after `evil-end-of-line` is already handled as it fakes being a `next-line` command.
In `evil-apply-on-block` only the case of `temporary-goal-column` equaling `most-positive-fixnum` is relevant, as other column values would be contained inside BEG..END.
Adds a test for commit 7aa71576d258b9546238f6dbd4cf5ca0a1b70088.
=> Simplify temporary-goal-column logic

evil-core.el
Hi,
When `evil` mode enable, the statement `(org-table-clean-line "|a|")` will run into dead loop.
https://lists.gnu.org/archive/html/emacs-orgmode/2022-12/msg00000.html
The root cause is the match data is changed by the advice function of `set-window-buffer` from evil.
The call chain is `(org-table-clean-line)` --> `(org-string-width)` --> `(set-window-buffer)`, and the in advice function of `set-window-buffer` will call the `eval-local-mode`, in which the match data is changed. 
This patch will fix the dead loop for the evil package should not affect the orgmode.
Please help review and apply the patch. Thanks
=> evil-core: fix dead loop that match data was changed in the advice function of  set-window-buffer

evil-common.el
Addresses https://github.com/emacs-evil/evil/issues/1074
- evil-with-undo:
nconc'ing onto front of buffer-undo-list here can corrupt buffer-undo-list
when in undo-tree-mode in rare circumstances (see issue #1074). Leave
standard undo machinery to work as usual when undo is enabled. Deal with
disabled undo by temporarily enabling then disabling undo, and transferring
any undo changes to evil-temporary-undo.
- evil-undo-pop:
This function called `undo' directly from Elisp, which is wrong when in
undo-tree-mode. Fix this by calling undo-tree-undo instead when in
undo-tree-mode.
=> Fix bugs in `evil-with-undo' and `evil-undo-pop' with undo-tree.

evil-commands.el, evil-tests.el
Searching through the results of `overlays-in`, in addition to looping with `next-overlay-change`/`overlays-at`, is essentially doing the same work twice. This commit opts for only doing the latter.
In addition, some other fixes are
* Avoid requiring flyspell.
* Fail immediately if no spelling error was found regardless of count, and signal error in that case so that macros are aborted like in Vim.
* Echo a notice when search wrapped around.
* Make `[s` and `s]` push the previous position onto the jump list.
* Run tests when suitable spell checker other than aspell is available.
=> Skip overlays-in in evil-next-flyspell-error

evil-commands.el, evil-common.el, evil-macros.el, evil-tests.el, evil-types.el
Instead of manually maintaining the cursor screen position with
```elisp
(let ((xy (evil-posn-x-y (posn-at-point))))
...
(goto-char (posn-point (posn-at-x-y (car xy) (cdr xy)))))
```
when scrolling via CTRL-U and CTRL-D, using the C functions `scroll-up`/`scroll-down` with `scroll-preserve-screen-position` set has the potential of being more performant.
=> Use scroll-preserve-screen-position for C-u/C-d

evil-common.el
`evil-jump-item` internally calls `evil-looking-at-start-comment`, which
fails at `point-max` because it checks `char-after` using `char-syntax`. Return
nil in it if `point` = `point-max`, because a comment cannot start at the end of
the buffer (it would be 0 characters long).
----
#
=> `evil-jump-item': don't error at `point-max'

evil-commands.el, evil-common.el, evil-core.el, evil-jumps.el, evil-states.el, evil-tests.el
This commit fixes some issues surrounding the initialization of Evil.
First of all, since GNU Emacs 26.1 major mode hooks actually do run in Fundamental mode buffers. In any case, manually enabling fundamental-mode correctly instead of turn-on-evil-mode (by setting major-mode default) successfully enables evil-local-mode, as major mode hooks then run. The major-mode variable also never needed to be reset; it is the job of the major mode to set it, as it starts off as fundamental-mode regardless of its default value.
Secondly, while some hooks and variables set up by evil-local-mode were marked as permanent, this did not matter as evil-initialize unconditionally reinitialized evil-local-mode whenever the major mode changed. Fixed by marking them all as permanent and not executing …
=> Fix Fundamental mode hack

evil-core.el
The predicate `(listp state)` is true also for the value `nil` of `state`, meaning the correct clause with `all-states` was never considered.
Closes #1383
=> Fix evil-set-leader with nil state argument

evil-core.el
This fixes the issue of the evil-send-(local-)leader commands being recognized as the motion while in Operator-pending state. Additionally, describe-key (C-h k) can now be used to lookup keybindings using leader.
Note that simply binding [(local-)leader] keyboard macros would not work, since then the command would not receive the prefix argument.
Closes #1711
=> Use extended-format menu item for leader bindings

evil-commands.el, evil-ex.el, evil-tests.el
This commit fixes a regression caused by #1549 where you could no longer give a prefix argument to execute the macro in an infinite loop.
=> Fix executing macro infinite times

evil-common.el, evil-macros.el, evil-tests.el, evil-types.el
Changing to Operator-pending state before executing
(evil-extract-count (this-command-keys))
can give the wrong result since the actual binding used to invoke the operator may not be present in the new state.
Resolves #1073
=> Use original state for populating shortcut map

evil-common.el, evil-states.el, evil-tests.el
The implementation of `evil-track-last-insertion` introduced in commit 477fe8e83e58739215ea3b601098ee134484114f assumed that all relevant changes look like atomic insertions/deletions, but e.g. `remove-yank-excluded-properties` upon yanking causes a single substitution change. This commit fixes that.
A change not centered around the end of the previous insertion is also made to start a new range, like in Vim.
Fixes #1759
=> Track composite changes to current insertion text

evil-commands.el, evil-common.el, evil-search.el, evil-tests.el
This fixes #1481.
Also pass along the number of the current replacement to function called to generate each replacement, which fixes #1411.
=> Restore match data after eval:ing replacement

evil-commands.el, evil-common.el, evil-repeat.el, evil-vars.el
As discussed in #857 and #858, the use of `read-key` in the evil-surround package broke `evil-repeat`, or `.`.  This is because `read-key` changes the result of `this-command-keys` just like `read-key-sequence`.  `read-key-sequence` is advised to fix this issue.  This patch merely gives the same advice to `read-key`, fixing the issues that have been caused by its use.
=> advise `read-key` as well as `read-key-sequence`

evil-core.el, evil-tests.el
This patch ensures that the input method after deactivating evil-local-mode is the same as the input method used for states with a non-nil :input-method property.
This issue was discovered while investigating why [the input method couldn't be set by the agda2-mode while evil was active][1]. As the change in major mode (to agda2-mode) caused evil-local-mode to be disabled and reenabled by `define-globalized-minor-mode evil-mode`, the input method was lost because the default state (i.e. normal state) does have an :input-method property of nil.
In summary this patch fixes [the approach used by agda2-mode][2] and the official recommendation for changing the input method in the [Emacs manual][3], e.g.
```elisp
(add-hook 'text-mode-hook
(lambda () (set-input-method "german-prefix")))
```
- …
=> Restore the input method on deactivation of evil-local-mode

evil-jumps.el
1. Add `evil-jumps-current-file-name-function` that returns `dired-directory` in `evil--jumps-push` when dired-mode is active. The `dired-directory` can be properly re-opened by `find-file` called by future evil-jump-backward or evil-jump-forward
2. Set property :jump to t for #'dired-find-file #'dired-goto-file and #'dired-up-directory
=> Support evil--jumps-push for dired-mode

evil-commands.el, evil-states.el, evil-tests.el
Repeating the pasted text for each line of the blockwise selection should only be done when the replacement text is characterwise and just a single line.
Resolves #1785
=> Fix pasting in visual block mode

evil-commands.el, evil-tests.el
The cursor should not be put after EOL if it has moved to a different line.
This commit also changes `evil--execute-normal-eol-pos` to be a marker, since the Normal state command may insert/remove text.
Closes #1804
=> Fix CTRL-O at BOL

evil-common.el, evil-tests.el
=> Select inner tag even when empty

evil-commands.el, evil-common.el, evil-tests.el, evil-vars.el
The function evil-visual-paste would assign to evil-visual-point/-mark the same markers used by the '[ and '] marks. Therefore after a single visual paste, Normal mode "gv" in that buffer would act funkily ever after. This commit fixes that.
Also removes unused definitions related to evil-visual-previous-point/-mark.
To reproduce:
* Enter new buffer with content:
```
x
y
```
* With cursor on `y`, type `ylvpkxgv`.
The expectation is that `y` should be re-selected. Instead the empty upper line is selected due to it being the previously changed text.
=> Stop the '[/'< and ']/'> marks from intertwining

evil-search.el
evil-search-wrap-ring-bell only worked when evil-search-module was isearch. Make it work with evil-search as well.
=> Make evil-search-wrap-ring-bell work with evil-search

doc/build/texinfo/evil.texi, doc/source/overview.rst
The URL [`https://vim.org`](https://vim.org) fails to resolve; this PR replaces the two instances of that in the docs to [`https://www.vim.org`](https://www.vim.org) which behaves as expected. This is already correct in [`README.md:12`](https://github.com/emacs-evil/evil/blob/master/README.md?plain=1#L12).
=> Fix Vim URL in docs

evil-commands.el, evil-maps.el
This emulates the behavior of vim, where {N}gt goes to the Nth tab, but {N}gT goes back N tabs.
=> tabs: Go to nth tab when tab-next is prefixed

evil-search.el, evil-tests.el
@axelf4 I noticed this bug recently and thought surely it must have been introduced recently, but I went back pretty far and could still replicate the bug, so I guess not. Nonetheless, I think you may have been closer to this area of code recently, so if you have any thoughts, feel free to have a stab at the fix. If not, I'll get to it in a few weeks, hopefully. Cheers
=> (Failing) test for `&` with very-magic vim-style backreferences

evil-common.el, evil-tests.el
Example of test:
```
{
fun(a, "T[]est", test());
}
```
With cursor at `[]`, the commands `])`, `[(`, `]}` or `[{` don't do anything.
This pull request fixes the problem.
=> Fix jumping to next/prev paren/brace from a string is not working

evil-commands.el, evil-maps.el, evil-tests.el
See "Changing tabs" section in the Vim manual
https://vimhelp.org/change.txt.html#change.txt
=> Add :retab command

evil-commands.el, evil-tests.el, evil-vars.el
Tests added for evil-goto-char. Fixes #1852
=> Declare goto-char as a motion, fix evil-goto-char

evil-core.el
It is useful to have clarification in the doc string for evil-define-key that it is necessary to escape modifiers keys, such as "C" and "M", for users that are accustomed to using functions like global-set-key or keymap-global-set where this is not necessary. This is also not made particularly clear in the define-key function itself, which is a legacy function.
=> Added clarification to evil-define-key for escaping modifier keys

evil-commands.el, evil-tests.el
=> No performant delete if range supplied

evil-commands.el
Fixes a warning:
evil-commands.el:2125:15: Warning: ‘backward-delete-char’ is for interactive use only; use ‘delete-char’ instead.
=> evil-commands: replace (backward-delete-char) with (delete-char)

evil-types.el
Split from #1860
This deprecation warning is targeted towards users' configuration. Having it warn about the variable being processed inside Evil is pointless, because of course it is processed in the mode, the mode have to handle it.
So suppress it by wrapping into `(with-no-warnings)`.
Fixes:
```
evil-types.el:96:22: Error: ‘evil-want-visual-char-semi-exclusive’ is an obsolete variable (as of 1.15.0);
```
=> evil-types.el: fix deprecation warning for Evil's internal variable

evil-commands.el, evil-tests.el
=> Always undo in normal state

evil-commands.el, evil-ex.el, evil-repeat.el, evil-tests.el
=> treewide: replace `(eq/equal foo nil)` with `(null foo)`

evil-commands.el, evil-tests.el
This fixes a regression caused by commit 004ac4e0cd766d49d48d53270e9c0c080ad9f173, where Visual mode "I" repeated the insertion on one too many lines unless at EOB.
=> Fix Visual Insert affecting one too many lines

evil-commands.el, evil-tests.el
Fixes an issue noticed while triaging #1894
=> Don't mutate register when stripping test props during paste

.readthedocs.yaml, doc/requirements.txt, doc/source/_ext/elisp.py
Read the Docs stopped installing spinx-rtd-theme by default, which broke documentation builds. This commit fixes that by pinning the required dependencies.
See: https://blog.readthedocs.com/defaulting-latest-build-tools/
=> Define documentation dependencies

evil-common.el, evil-tests.el
=> Backreferences in vim-style regexp

.github/workflows/test.yml, .gitignore, Cask, Eask, Makefile, evil-pkg.el, evil-tests.el
Proposed in https://github.com/emacs-evil/evil/issues/1882#issuecomment-2046965282.
=> ci: Use Eask to test macos and windows

evil-core.el
Fixes https://github.com/emacs-evil/evil/issues/502, fixes https://github.com/emacs-evil/evil/issues/1835. Refreshing the cursor when changing the evil state is
only needed (or almost only, see below) when the current buffer is displayed in the
selected window. If this is not the case, and the buffer is only displayed or
its window selected at some later point in time, then `evil-refresh-cursor` will
be called as part of the `window-configuration-change-hook` or as advice to
`select-window`.
However, this introduces the following tiny (and maybe acceptable?) regression:
When doing something like
```elisp
(with-current-buffer some-buffer-displayed-in-another-window
(some-evil-state-with-a-different-cursor-type))
```
the cursor will not be refreshed in the other window before selecting it. …
=> Fix cursor colour

evil-commands.el
Also temporarily disable pre- and post-command hooks
=> Combine after change calls during macro execution

evil-jumps.el, evil-tests.el
Steps to reproduce the issue:
- Create files `a` `b` `c` with the following content:
```
$ head a b c
==> a <==
b
I'm A
==> b <==
c
I'm B
==> c <==
I'm C
```
- Run `emancs a` to open bufer `a`
- Press `gf` to jump to bufer `b`
- Press `gf` to jump to bufer `c`
- Press `C-o` to jump back to bufer `b`
- Press `C-o` to jump back to bufer `a`
- Press `C-i` to jump foward to bufer `b`
- Press `C-i` to jump foward to bufer `c`, but the window stays on buffer `b` unexpectedly.
=> Fix: Should not (evil-set-jump previous-pos) jump after evil-jump-forward

evil-ex.el
Means that :de expands to delete
=> Bind all possible ex cmd abbreviations

evil-common.el
When in the point is on a blank line in normal state, scrolling down with `pixel-scroll-precision-mode` enabled "sticks" because Evil ends up invoking `line-move` in the `post-command-hook`. `line-move` resets vscroll to 0, which undoes the scroll if we scrolled less than a line.
Specifically, `evil-normal-post-command` calls `evil-adjust-cursor` which calls `evil-move-end-of-line` which calls `move-end-of-line`, which finally calls `line-move`.
This change avoids this issue by avoiding `evil-move-end-of-line` entirely, instead using `bolp` to check if we're already at the beginning of the line.
(note: I'm not sure if there were subtle reasons for calling `evil-move-end-of-line` here)
Upstream bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=72323. But Evil probably shouldn't be …
=> Fix pixel-scroll-precision-mode when point is on a blank line

.gitignore, Eask, Makefile, evil-common.el, evil-core.el, evil-ex.el, evil-integration.el, evil-keybindings.el, evil-macros.el, evil-pkg.el, evil-repeat.el, evil-search.el, evil.el
The original motivation was to fix the misuse of `eval` in `evil-delay` by turning it into a macro (name `evil-with-delay`).  But it includes various generic changes such as prefering #' to quote function names and fixing some incorrect uses of ' in docstrings (many warnings remain about this).
The patch also enables `lexical-binding` in the remaining files. `lexical-binding` in `evil-ex.el` has had a tumultuous life, the last commit of which sets it explicitly to nil while stating confusingly in the commit message that it re-enables it.  In any case, I still found some changes needed to account for `lexical-binding`, so there might be more.
Detailed changes below.
* evil-common.el (evil-unquote): Delete function, not used (luckily: it reeked of a bad hack to work around a misunderstood …
=> Various code cleanups

evil-vars.el
The new editorconfig-mode in Emacs 30 automatically sets evil-shift-width ([here](https://github.com/emacsmirror/emacs/blob/8d687695c528e4edb04cca5602470d349e333258/lisp/editorconfig.el#L465)), but a popup window is shown every time because this variable is not marked safe as a local variable. This PR marks it safe to get rid of this annoyance.
=> Make evil-shift-width safe as local variable

evil-commands.el
Undo in region can be very useful and is supported by all undo backends. Before #1888, `evil-undo` stayed in visual state, and I think restoring this behaviour should not negatively affect the fix for #1883.
=> Allow `evil-undo` in visual state again (undo in region)

evil-commands.el
Emacs 30 introduces improved touch-screen support (via the Android port), see “Touchscreen Events” in the Emacs Lisp reference manual: By default, touch screen gestures are not processed when a command is bound to `down-mouse-1` (as `evil-mouse-drag-region` is), as that is taken as an indication that touch input should be translated to `down-mouse-1` followed by mouse motion events.
This change applies the `ignored-mouse-command` property to `evil-mouse-drag-region` that is also present on `mouse-drag-region` in Emacs 30.  This has the effect that touch screen gestures are prioritized and mouse events are only emitted when no gesture was detected.
=> Fix touch screen gestures (e.g., scrolling) for Emacs 30

evil-vars.el
```
»  Warning (comp): evil-vars.el:561:25: Warning: the function `evil-delete-backward-word' is not known to be defined.
»  Warning (comp): evil-vars.el:565:25: Warning: the function `evil-delete-backward-word' is not known to be defined.
```
=> Fix Emacs warnings
